# Generated by Django 6.0.4 on 2026-04-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, verbose_name='رقم القضية')),
                ('court_name', models.CharField(max_length=200, verbose_name='اسم المحكمة')),
                ('case_type', models.CharField(choices=[('commercial', 'تجارية'), ('civil', 'مدنية'), ('criminal', 'جنائية'), ('labor', 'عمالية'), ('family', 'أسرية'), ('administrative', 'إدارية'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='نوع القضية')),
                ('opponent_name', models.CharField(max_length=200, verbose_name='اسم الخصم')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('postponed', 'مؤجلة')], default='open', max_length=20, verbose_name='حالة القضية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'قضية',
                'verbose_name_plural': 'القضايا',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(verbose_name='تاريخ الجلسة')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('held', 'منعقدة'), ('postponed', 'مؤجلة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=20, verbose_name='حالة الجلسة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['-session_date'],
            },
        ),
    ]
