# Generated by Django 5.2.13 on 2026-05-01 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseexpense_invoice'),
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان الطلب')),
                ('request_type', models.CharField(choices=[('expense', 'اعتماد مصروف'), ('discount', 'اعتماد خصم'), ('contract', 'اعتماد عقد'), ('legal_step', 'إجراء قانوني'), ('other', 'أخرى')], default='other', max_length=30, verbose_name='نوع الطلب')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة مرتبطة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='تفاصيل')),
                ('decision_note', models.TextField(blank=True, verbose_name='ملاحظة القرار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القرار')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_to_review', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول الاعتماد')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='cases.case', verbose_name='القضية')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
            ],
            options={
                'verbose_name': 'طلب موافقة',
                'verbose_name_plural': 'طلبات الموافقة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان العقد')),
                ('start_date', models.DateField(verbose_name='بداية العقد')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='نهاية العقد')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قيمة العقد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('expired', 'منتهي'), ('terminated', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('document_ref', models.CharField(blank=True, max_length=255, verbose_name='مرجع ملف العقد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='cases.case', verbose_name='القضية')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الجهة')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المسؤول')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('stage', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('qualified', 'مؤهل'), ('proposal', 'عرض سعر'), ('won', 'تم التحويل'), ('lost', 'مفقود')], default='new', max_length=20, verbose_name='المرحلة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('converted_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='companies.company', verbose_name='الشركة بعد التحويل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'عميل محتمل',
                'verbose_name_plural': 'العملاء المحتملون',
                'ordering': ['-created_at'],
            },
        ),
    ]
