# Generated by Django 6.0.4 on 2026-04-25 05:46

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to=apps.documents.models.upload_path, validators=[apps.documents.models.validate_file_extension, apps.documents.models.validate_file_size], verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('image', 'صورة'), ('excel', 'Excel'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الملف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case', verbose_name='القضية')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
