# Generated by Django 4.2.30 on 2026-04-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='متصل الآن'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_device',
            field=models.CharField(blank=True, max_length=300, verbose_name='آخر جهاز'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('developer', 'مطور النظام'), ('admin', 'مدير النظام'), ('lawyer', 'محامي'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='الدور الوظيفي'),
        ),
    ]
