# Generated by Django 4.2.30 on 2026-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_online_customuser_last_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_view_online',
            field=models.BooleanField(default=False, verbose_name='يمكنه مشاهدة المتصلين'),
        ),
    ]
